version: '2'

services:
    zookeeper2:
      container_name: zookeeper2
      network_mode: host
      image: hyperledger/fabric-zookeeper:latest
      restart: always
      ports:
      - '2181'
      - '2888'
      - '3888'
      environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=10.0.0.250:2888:3888 server.2=10.0.0.251:2888:3888 server.3=10.0.0.252:2888:3888
