version: '2'

services:
    ca.org2.oslab.com:
        image: hyperledger/fabric-ca:1.4.1
        environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=ca.org2.oslab.com
        - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.oslab.com-cert.pem
        - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca2_key
        # - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/key.pem
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.org2.oslab.com-cert.pem
        - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/ca2_tls_key
        # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/key.pem

        ports:
        - "8054:7054"
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
        - ../../config/config-kafka_325_batch_100/crypto-config/peerOrganizations/org2.oslab.com/ca/:/etc/hyperledger/fabric-ca-server-config
        - ../../config/config-kafka_325_batch_100/crypto-config/peerOrganizations/org2.oslab.com/tlsca/:/etc/hyperledger/fabric-ca-server-tls
        container_name: ca.org2.oslab.com
