version: '2'

services:
    orderer2.oslab.com:
        container_name: orderer2.oslab.com
        image: hyperledger/fabric-orderer:1.4.1
        environment:
        - FABRIC_LOGGING_SPEC=grpc=debug:debug
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        - ORDERER_GENERAL_GENESISMETHOD=file
        - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
        - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
        - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
        - ORDERER_GENERAL_TLS_ENABLED=true
        - ORDERER_KAFKA_VERBOSE=true
        - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
        - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
        - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/msp/orderer/tls/ca.crt]
        # - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
        # - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: orderer
        ports:
        - 9050:7050
        volumes:
        - ../../config/config-kafka_325_batch_100/:/etc/hyperledger/configtx
        - ../../config/config-kafka_325_batch_100/crypto-config/ordererOrganizations/oslab.com/orderers/orderer2.oslab.com/:/etc/hyperledger/msp/orderer

        extra_hosts:
        - "ca.org1.oslab.com:192.168.0.136"
        - "kafka0:192.168.0.147"
        - "kafka1:192.168.0.148"
        - "kafka2:192.168.0.149"
        - "kafka3:192.168.0.150"
