version: '2'

services:
    kafka2:
      container_name: kafka2
      image: hyperledger/fabric-kafka
      restart: always
      environment:
      - KAFKA_MESSAGE_MAX_BYTES=157286400 # 1 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=157286400 # 1 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=true
      - KAFKA_BROKER_ID=2
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=192.168.0.137:2181,192.168.0.139:2181,192.168.0.138:2181
      ports:
      - '9092'
      extra_hosts:
      - zookeeper0:192.168.0.137
      - zookeeper1:192.168.0.139
      - zookeeper2:192.168.0.138
